<Project>

	<PropertyGroup>
		<VoidstrapVersion>6.7.7.7</VoidstrapVersion>
	</PropertyGroup>

	<PropertyGroup>
		<Version Condition="'$(Version)' == ''">$(VoidstrapVersion)</Version>
		<FileVersion>$(Version)</FileVersion>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<InformationalVersion>$(Version)</InformationalVersion>
	</PropertyGroup>

</Project>
