<Project>

	<PropertyGroup>
		<VoidstrapVersion>1.1.2.4</VoidstrapVersion>
	</PropertyGroup>

	<PropertyGroup>
		<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(VoidstrapLinuxPackagingRoot)' != ''">
		<BaseOutputPath>$(VoidstrapLinuxPackagingRoot)bin/$(MSBuildProjectName)/</BaseOutputPath>
		<BaseIntermediateOutputPath>$(VoidstrapLinuxPackagingRoot)obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
		<DefaultItemExcludes>$(DefaultItemExcludes);bin/**;bin-*/**;bin-cross/**;obj/**;obj-*/**</DefaultItemExcludes>
	</PropertyGroup>

	<PropertyGroup Condition="'$(VoidstrapLinuxPackagingRoot)' != '' And $(MSBuildProjectName.StartsWith('Voidstrap.Cross'))">
		<BaseOutputPath>$(VoidstrapLinuxPackagingRoot)bin/Voidstrap.Cross/</BaseOutputPath>
		<BaseIntermediateOutputPath>$(VoidstrapLinuxPackagingRoot)obj/Voidstrap.Cross/</BaseIntermediateOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<Version Condition="'$(Version)' == ''">$(VoidstrapVersion)</Version>
		<FileVersion>$(Version)</FileVersion>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<InformationalVersion>$(Version)</InformationalVersion>
	</PropertyGroup>

</Project>
