<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
		<SupportedOSPlatformVersion>10.0.14393.0</SupportedOSPlatformVersion>
		<OutputType>WinExe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Voidstrap.Desktop.Windows</RootNamespace>
		<AssemblyName>Voidstrap.Desktop.Windows</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Voidstrap.Desktop\Voidstrap.Desktop.csproj" />
		<ProjectReference Include="..\Voidstrap.Platform.Windows\Voidstrap.Platform.Windows.csproj" />
	</ItemGroup>
</Project>
