<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>Voidstrap.Platform.Linux</RootNamespace>
		<AssemblyName>Voidstrap.Platform.Linux</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Voidstrap.Core\Voidstrap.Core.csproj" />
		<ProjectReference Include="..\Voidstrap.Platform.Abstractions\Voidstrap.Platform.Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Tomlyn" Version="2.10.1" />
	</ItemGroup>
</Project>
