<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Voidstrap.Core</RootNamespace>
		<AssemblyName>Voidstrap.Core</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Voidstrap.Platform.Abstractions\Voidstrap.Platform.Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="..\Voidstrap.App\Models\Persistable\AppSettings.cs" LogicalName="Catalog/AppSettings.cs" Visible="false" />
		<EmbeddedResource Include="..\Voidstrap.App\UI\Elements\Settings\SearchCatalog.cs" LogicalName="Catalog/SearchCatalog.cs" Visible="false" />
		<EmbeddedResource Include="..\Voidstrap.App\UI\Elements\Settings\Pages\*.xaml" LogicalName="Catalog/Pages/%(Filename)%(Extension)" Visible="false" />
	</ItemGroup>
</Project>
